#
# test using QEMU
#
name: unittest (emulated by QEMU)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu:
          - "atmega168p"
          - "atmega328p"
          - "atmega2560"

    steps:
      - uses: "actions/checkout@v3"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: configure for ${{matrix.mcu}}
        run: |
          mkdir build
          cd build
          cmake .. -DAVR_SERIAL_BUILD_TESTS=ON -DAVR_MCU=${{matrix.mcu}}

      - name: build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: test
        working-directory: ${{github.workspace}}/build
        run: ctest
